### ISSUE TITLE
Query expansion using word embeddings

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#13]
Idea: expand topics (disease + gene) with the `k` most similar words according to e.g. BioWordVec.

Ideally, this would guess the following mappings:
- Disease synonyms
- Disease hypernyms (including "solid" rule)
- Gene synonyms (STK11 = LKB1)
- Gene hypernyms/families (BRCA2 < BRCA)

Caveat: sibling genes/diseases might be pulled in.

**Comment by khituras** [comment]
You mean to add words based on word vector similarity to topic fields?

**Comment by michelole** [comment]
Yes, updated the description.

**Comment by michelole** [comment]
There's some e[vidence in literature](https://www.aclweb.org/anthology/P16-1035) that local word embeddings are better than global ones.

**Comment by khituras** [comment]
What does local and global mean here? Contextualised vs static?

**Comment by michelole** [comment]
Trained on documents per topic _versus_ trained on the full corpus.

**Comment by michelole** [comment]
Implementation of this could be via #52 .

**Comment by michelole** [comment]
http://bio.nlplab.org/ embeddings seems to be much better than BioWordVec, so we're using them.
