### ISSUE TITLE
UMLS disease hypernyms

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#19]
Move away from the proprietary Lexigram API and use the UMLS files directly for hypernym disease expansion.

Ideally, we would have different ancestor levels, so that we can control the refinement required (and not every topic is also "disease by site").

**Comment by khituras** [comment]
Excuse me, what does "disease by site" mean? :-)

**Comment by michelole** [comment]
Sorry, it should be  [disorder by body site](https://browser.ihtsdotools.org/?perspective=full&conceptId1=123946008&edition=en-edition&release=v20190131&server=https://prod-browser-exten.ihtsdotools.org/api/snomed&langRefset=900000000000509007): it's the parent concept of all diseases, so not specific at all...

**Comment by michelole** [comment]
This is a "nice-to-have" iff we can control the number of parent ancestors. Otherwise we can live with Lexigram for now.

**Comment by khituras** [comment]
With the number of ancestores you mean the distance, right?

**Comment by michelole** [comment]
Fixed by https://github.com/JULIELab/trec-pm/pull/45.
