### ISSUE TITLE
Index new snapshots

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#3]
TREC-PM 2019 uses a more recent snapshot of ClinicalTrials.gov and MEDLINE, we should download and index it in ES.

**Comment by michelole** [comment]
Can we marked this as fixed?

**Comment by khituras** [comment]
Not yet, working on the CT part right now.

**Comment by khituras** [comment]
As of now there is also the `trecpm19_ct_bm25` index. Closing this issue.
