### ISSUE TITLE
It's not only about cancer

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#48]
2019 topics are not only about cancer (e.g. topic 32) and we get false matches because of that. Consider removing the keyword or reducing boost.

Caveat: if removed as a boost, it should be removed from stopwords as well.

**Comment by michelole** [comment]
Also we should make our rule for "solid cancer" smarter.

**Comment by khituras** [comment]
Ich think we could include the UMLS semantic types:
neop|T191|Neoplastic Process
is assigned to the cancer-concepts, I think/hope, it is at least for melanoma.

This can be used to filter the concepts used for synonymy and relatives.
