### ISSUE TITLE
`Retrieval` should not depend on year

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#50]
It's confusing that both `Experiment` and the encapsulated `Retrieval` depend on year.

`Experiment` requires it to guess the topics to load (given also the `Task`), which makes sense.

However, `Retrieval` uses it only for the experimentID, which is misleading. Moreover, `Retrieval` is designed to accept topics from different years (via the `retrieve` method), so it should not fix a single year.

**Comment by khituras** [comment]
Agreed. This, and a few other quirks, exist because I wanted to keep compatibility with the old experimental code. We are free to change that now.
