### ISSUE TITLE
`Experiment` should not depend on `Task`

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#51]
`Task` is everywhere: in the Topic and TopicSet (#23), in the GoldStandard (OK), in `Retrieval` (both as attribute and indirectly in the method `retrieve`, some discussion at #23), and in the `Experiment`.

It's used in the `Experiment` to initialize both a TopicSet and a gold standard (#16 , #17).

However, since an `Experiment` depends on a `Retrieval`, `Experiment` should either
(a) use the task set in `Retrieval`; or
(b) don't depend on a task at all (if the classes are reused for different tasks).

Since I believe `Retrieval` and `Experiment` should not be reused for different tasks (and thus the task can be removed from Topic), I vote for (a) here.

**Comment by khituras** [comment]
I'm sure which "it" refers to `Experiment` or to `Retrieval` :-D I would say that the `Experiment` should know the task. The `Retrieval` should be largely agnostic about what it retrieves for which purpose, it should just do its job.

**Comment by michelole** [comment]
Updated comment to make it less ambiguous. I'll comment on an agnostic `Retrieval` on #23 to centralize the discussion there.

**Comment by michelole** [comment]
At some point, `Retrieval` will have only the index, but not the task anymore (#56 ).
Anyway, `Experiment` depends on GS, which has the task already.

**Comment by michelole** [comment]
Fixed in 254e93e68a03c47f03cdeb9ce219f52bf05d77f3.
