### ISSUE TITLE
Migrate code to ES 7

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#55]
- Types are not supported anymore
    - Deprecate (remove?) constructor with types in `ElasticSearchQuery`
    - Will we still support AACR/ASCO abstracts for 2017/2018? If yes, how?
- Other ES changes...

**Comment by khituras** [comment]
Oh. I'm afraid we didn't have AACR/ASCO boosting in the last year. Reason: I put them all into the same type. I am very sorry about that. I had already introduced a new field `documentSource` which has the values `PUBMED`, `ASCO` or `AACR`. This should have been used for boosting but I never did. But this is how we will support it in the future...

**Comment by michelole** [comment]
Negative boosts are being handled on #73

**Comment by michelole** [comment]
Since we're able to run experiments without negative boosts, I'm closing this one.
