### ISSUE TITLE
Punish empty papers about genes

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#75]
E.g. https://www.ncbi.nlm.nih.gov/pubmed/16521281

**Comment by khituras** [comment]
What do you mean with "on genes"?
I just tried a bit and found that this works quite well:

    {
      "query": {
        "boosting": {
          "positive": {
            "match": {
              "title": "RYR1"
            }
          },
          "negative": {
            "bool": {
              "must_not": {
                "exists": {
                  "field": "abstract"
                }
              }
            }
          },
          "negative_boost": 0.5
        }
      }
    }

One can see very nice how documents without abstracts are pushed down with the `negative_boost`<1 and how they are pulled up with >1.

**Comment by michelole** [comment]
"on genes": pseudo-papers like the example that pretend to talk about a specific gene.

So far I was filtering this with `must_not` "gene symbol" (pending evaluation), but if there's such a clause `exists`, it should be the way to go.

Not sure if this should be negatively-boosted or a hard requirement though.
