### ISSUE TITLE
Create manual curated filter list for treatments

### ISSUE THREAD

**Issue by khituras** [JULIELab/trec-pm#77]
This concerns e.g. #76. Some treatment words are "various" and other probably non-helpful stuff. Those should be filtered out. The easiest way would be to remove such words from the index directly.
When creating filter lists, check out if the `broadTreatments` field is mainly containing the bad candidates and whether `focusedTreatments` fares significantly better. Also check whether the focused field is missing good treatment concepts which occur in the broad field.

**Comment by michelole** [comment]
Blocked on #41 (and somehow, #42).

**Comment by michelole** [comment]
Check whether the `broadTreatments` contain e.g. surgery and radiotherapy, which are valid treatments currently not found with the `focusedTreatments`.

**Comment by michelole** [comment]
Fixed by cf97263800cdb4aa6b9518dedf48facd424e9850. `broadTreatments` seem to only add additional noise with no benefit. I'm happy with the filtered `focusedTreatments` so far.
