### ISSUE TITLE
Boost documents from GS

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#78]

**Comment by michelole** [comment]
@khituras Are `inOfficial2018gs` fields ready?

**Comment by khituras** [comment]
They will be contained in the index, yes.

**Comment by khituras** [comment]
What would you use this information for?

**Comment by michelole** [comment]
Thought about boosting documents in GS as a signal, but just noticed that also docs ranked 0 are there, so closing as won't fix.
