### ISSUE TITLE
`Experiment` could receive an optional `Ranker`

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#79]
It would then re-rank docs automatically given a pre-trained model.

Could be used for LTR (#44 ) and Treatment ranking (#28 ).

**Comment by khituras** [comment]
Should the ranker perhaps even be added to the retrieval directly?

**Comment by michelole** [comment]
Nope. I see `Retrieval` as a convenient way to run decorated topics on ES and only that. A `Ranker` is optional and should work upon a list of documents, no matter where they came. This would even allow manual runs (e.g. submitting the internal GS), that could be re-ranked for treatments.

**Comment by khituras** [comment]
Understood.
