### ISSUE TITLE
Adapt current framework version for ES5.4

### ISSUE THREAD

**Issue by khituras** [JULIELab/trec-pm#84]
I haven't started this yet, @michelole  can go if required/wanted. Would do it tomorrow morning, otherwise. But it is late, I cant guaranty I will be very early.

**Comment by khituras** [comment]
I have done the switch to ES5.4, test are running, but results are still wrong. Investigating and re-creating the indices.

**Comment by michelole** [comment]
Fixed by b2906316d498bb36283520bae320149ab5242c9b.
